name: zz ❌❌ DO NOT USE (WIP)
description: Submit a bug or error report.
labels: ['Needs: Triage', 'type:bug-suspected']

body:
- type: markdown
  attributes:
    value: |
      - [x] Bug

      This is for SharePoint development bugs. If your submission is now about SharePoint development such as out-of-the-box capabilities, SharePoint configuration, please use refer to other support options listed on the [new issue chooser page](https://github.com/SharePoint/sp-dev-docs/issues/new/choose). Please provide as much information as possible so we can best address your submission. Thanks!

      - Follow our guidance on [How To Create Good Issues](https://github.com/sharepoint/sp-dev-docs/wiki/How-to-Create-Good-Issues).
      - Remember to include sufficient details and context.
      - If you have multiple questions, suggestions, or bugs, please submit them in separate issues.

      Please provide the following details about your environment. 🚨  *If this section is ignored, your submission will be flagged as **incomplete** & automatically closed.*

- type: dropdown
  attributes:
    label: Target SharePoint environment
    options:
      - SharePoint Online
      - SharePoint Server 2019 (on-premise)
      - SharePoint Server 2016 (on-premise)
      - other (enter in the "Additional environment details" area below)
  validations:
    required: true

- type: dropdown
  attributes:
    label: What SharePoint development model, framework, SDK or API is this about?
    description: |
      What tooling, frameworks, SDKs, or official libraries is this related to? Please include the version details in the *"Additional environment details"* field below.

      **This form is only for officially supported Microsoft products**.

      *If your question is about a third-party or another library/SDK/tooling that is not officially supported by Microsoft, please submit your issue to that project's relevant forum.*

      **NOTE**:💥 If you select SharePoint Framework, you must include the following version numbers in the **Additional environment details** section below: 1️⃣  SharePoint Framework & 2️⃣  Node.js (`node -v`).
    options:
      - 💥 SharePoint Framework
      - SharePoint Add-ins
      - SharePoint CSOM
      - SharePoint REST API
      - not applicable
      - other (enter in the "Additional environment details" area below)
  validations:
    required: true

- type: dropdown
  attributes:
    label: Developer environment
    options:
      - Windows
      - macOS
      - Linux
