name: Bug / error report
description: Submit a bug or error report.
labels: ['Needs: Triage', 'type:bug-suspected']

body:
- type: markdown
  attributes:
    value: |
      - [x] Bug

      This is for SharePoint development bugs. If your submission is now about SharePoint development such as out-of-the-box capabilities, SharePoint configuration, please use refer to other support options listed on the [new issue chooser page](https://github.com/SharePoint/sp-dev-docs/issues/new/choose). Please provide as much information as possible so we can best address your submission. Thanks!

      - Follow our guidance on [How To Create Good Issues](https://github.com/sharepoint/sp-dev-docs/wiki/How-to-Create-Good-Issues).
      - Remember to include sufficient details and context.
      - If you have multiple questions, suggestions, or bugs, please submit them in separate issues.

- type: markdown
  attributes:
    value: |
      Please provide the following details about your environment. *If this section is ignored, your submission will be flagged as **incomplete** & automatically closed.*

- type: dropdown
  id: target_environment
  attributes:
    label: Target SharePoint environment
    options:
      - SharePoint Online
      - SharePoint Server 2019 (on-premise)
      - SharePoint Server 2016 (on-premise)
      - other (enter in the "Additional environment details" area below)
  validations:
    required: true

- type: checkbox
  id: tooling
  attributes:
    label: Tooling / frameworks / Microsoft libraries
    description: |
      What tooling, frameworks, SDKs, or official libraries is this related to? Please include the version details in the *"Additional environment details"* field below.

      **This form is only for officially supported Microsoft products**.

      *If your question is about a third-party or another library/SDK/tooling that is not officially supported by Microsoft, please submit your issue to that project's relevant forum.*
    options:
      - Visual Studio Code (include version below)
      - Visual Studio (include version below)
      - .NET (include version below)
      - Node.js (include version below)
      - SharePoint Framework (include version below)
      - SharePoint Add-ins
      - SharePoint CSOM
      - SharePoint REST API
      - not applicable
      - other (enter in the "Additional environment details" area below)
  validations:
    required: true
